<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Ae.Sample.Identity</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ae-sample-identity-lib\ae-sample-identity-lib.csproj" />
  </ItemGroup>

</Project>
